# Generated by Django 3.2.8 on 2021-11-23 03:16

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_complaintsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsdetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
