# Generated by Django 3.2.8 on 2021-11-23 04:43

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_complaintsdetails_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsdetails',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='send_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsdetails',
            name='send_sms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
